### ISSUE TITLE
How about checking via AJax also :) ?

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/yii2-widget-growl#3]

**Comment by sanjarbek** [comment]
The same problem. Not work via ajax.

**Comment by kartik-v** [comment]
You need to write your own javascript code to initialize via ajax or any such similar cases at runtime... since Yii or PHP will not be able to help you there.

**Comment by sanjarbek** [comment]
I mean it does not work inside pjax. But if you said it is not bug, it is ok.
